import hashlib
import os
import shutil
import tomllib
from collections.abc import Generator
from contextlib import contextmanager
from pathlib import Path
from typing import Annotated

import tomlkit
from cyclopts import Parameter
from packaging.utils import canonicalize_name
from plumbum import local
from plumbum.commands.processes import CommandNotFound
from pydantic import ValidationError
from rich.console import Console

from . import ENV_DIR, MANIFEST, NAME, PIXI_RESOLVED, PYPROJECT
from .backends import Cargo, Node, Pixi
from .base import Toml
from .compiled import PackageJson, PixiManifest
from .console import markup
from .environment import Environment
from .errors import ChefeError, manifest_validation_text
from .generated import GeneratedFiles
from .global_env import GlobalEnv
from .manifest import Document, Manifest, Spec, ToolchainSpec, find_manifest
from .state import Declared
from .tree_report import KIND_SOURCES, TreeReport
from .utils import current_platform

# Records the manifest digest a sync compiled from, so a later command can tell when the
# generated env has gone stale against an edited manifest and recompile before activating.
SYNCED = ".synced"

# Records local project metadata that Pixi resolves but chefe.toml does not contain.
_RESOLUTION_INPUTS = ".resolution-inputs"

# Present when the lock no longer matches the resolution inputs. Written instead of deleting
# `pixi.lock`, so a workspace shared by several processes always keeps a usable lock while one
# of them is still solving, and a solve that fails leaves the previous environment intact.
_RESOLUTION_STALE = ".resolution-stale"

# The generated per-host activation script, beside the compiled pixi manifest.
ACTIVATE = "activate.sh"

# The generated dotenv loader, sourced first by pixi activation when `workspace.dotenv` is on.
# Activation scripts run from the manifest dir (`.chefe/`), so `../.env` is the workspace root.
DOTENV = "dotenv.sh"
DOTENV_SH = (
    "#!/usr/bin/env bash\n"
    "# Generated by `chefe sync` (workspace.dotenv = true); do not edit by hand.\n"
    "set -a\n"
    '[ -f "../.env" ] && . "../.env"\n'
    "set +a\n"
)


class PackageManager:
    """A workspace: one manifest, compiled into a generated env and run by the real tools."""

    def __init__(self, root: Path | None = None) -> None:
        # Absolute so the env bin dirs put on PATH stay valid when a backend runs
        # from inside the env: a relative npm path breaks once the cwd changes.
        root = (root if root is not None else self.discover()).absolute()
        self.manifest = find_manifest(root) or root / MANIFEST
        self.root = root
        self.out = root / ENV_DIR
        self.activate_path = self.out / ACTIVATE
        self.pixi = Pixi(self.out)
        self.cargo = Cargo(self.out, self.pixi)
        self.console = Console()
        self.glob = GlobalEnv(self.pixi, self.load, self.console)
        self.report = TreeReport(self.console)

    @staticmethod
    def discover(start: Path | None = None) -> Path:
        """Walk up from ``start`` (default cwd) to the nearest dir holding the manifest.

        Running chefe from a subdir should still find its workspace, the way git locates `.git`.
        Falls back to ``start`` itself when no manifest is found, so `chefe init` in a fresh dir
        still scaffolds there and `load()` later raises the actionable not-found error.
        """
        start = (start or Path()).absolute()
        for directory in (start, *start.parents):
            if find_manifest(directory) is not None:
                return directory
        return start

    def load(self) -> Manifest:
        """The validated manifest."""
        if not self.manifest.exists():
            raise ChefeError(
                f"{self.manifest.name} not found. "
                "Run `chefe init` first, or run chefe from a workspace root."
            )
        try:
            return Manifest.load(self.manifest)
        except tomllib.TOMLDecodeError as error:
            raise ChefeError(f"{self.manifest.name} has invalid TOML: {error}") from error
        except ValidationError as error:
            raise ChefeError(manifest_validation_text(self.manifest, error)) from error

    def editable_manifest(self) -> None:
        """Refuse to rewrite a manifest embedded in `pyproject.toml`.

        `install` and `run` only read, so they work everywhere. The in-place writers
        (`add`/`remove`/`upgrade`) do not: a runtime dep belongs in `[project.dependencies]` and a
        tool in `[tool.chefe]`, so which table a package lands in is ambiguous for an embedded
        manifest. They point at the file to edit by hand rather than guess.
        """
        if self.manifest.name == PYPROJECT:
            raise ChefeError(
                f"`{NAME}` cannot edit the [tool.{NAME}] manifest inside {PYPROJECT}. "
                f"Edit {PYPROJECT} by hand: runtime deps under [project.dependencies], "
                f"tools and tasks under [tool.{NAME}]."
            )

    def node(self, manifest: Manifest, env: str = "default") -> Node:
        """The Node.js backend for ``env``'s merged toolchain: manager binary plus install dir."""
        nodejs = manifest.toolchains_for(env, current_platform()).get("nodejs")
        app = nodejs.app if nodejs is not None else False
        manager = nodejs.manager if nodejs is not None and nodejs.manager else "npm"
        directory = self.root if app else self.out
        return Node(directory, manager)

    def declared(self, env: str) -> dict[str, Declared]:
        """Every dep declared for ``env`` on this host."""
        return self.load().declared(env, current_platform())

    @contextmanager
    def activated(self, env: str = "default") -> Generator[None]:
        """Expose managed ecosystem executables on PATH for commands and shells.

        Recompiles first when the manifest changed since the last sync, so an edit to
        `chefe.toml` (a new env var, a dep) is never served from a stale generated env.
        """
        if self.stale(env):
            self.console.print(
                markup(t"[yellow]{self.manifest.name} changed, recompiling[/yellow]")
            )
            self.sync(env)
        with self.pixi.activated(env):
            manifest = self.load()
            toolchains = manifest.toolchains_for(env, current_platform())
            binary_dirs = [
                self.node(manifest, env).binary_dir(),
                *[self.out / path for spec in toolchains.values() for path in spec.bin_dirs],
            ]
            path = local.env["PATH"]
            prefix = os.pathsep.join(str(path) for path in binary_dirs if path.is_dir())
            with local.env(PATH=f"{prefix}{os.pathsep}{path}" if prefix else path):
                yield

    def init(self, name: str = "") -> None:
        """Scaffold a starter manifest."""
        if self.manifest.exists():
            self.console.print(f"[yellow]{self.manifest.name} already exists[/yellow], untouched")
            return
        name = name or Path.cwd().name
        self.manifest.write_text(
            f'[workspace]\nname = "{name}"\nversion = "0.1.0"\n'
            f'platforms = ["{current_platform()}"]\n'
            'channels = ["conda-forge"]\n\n[deps]\npython = ">=3.11"\n'
        )
        self.console.print(
            markup(t"[green]created[/green] {self.manifest.name} for [bold]{name}[/bold]")
        )

    def digest(self) -> str:
        """A content hash of the manifest, the key that decides whether a compile is current."""
        return hashlib.sha256(self.manifest.read_bytes()).hexdigest()

    def _resolution_digest(self, manifest: Manifest) -> str:
        """Hash local project metadata that can change without changing the compiled manifest."""
        digest = hashlib.sha256()
        for declared in manifest.local_python_projects():
            project = self.root / declared / PYPROJECT
            digest.update(declared.encode())
            try:
                digest.update(project.read_bytes())
            except FileNotFoundError:
                digest.update(b"\0")
        return digest.hexdigest()

    @staticmethod
    def _resolution_manifest(text: str) -> dict[str, Toml]:
        """Return generated Pixi data that can affect dependency resolution."""
        document = tomllib.loads(text)
        document.pop("tasks", None)
        return document

    def stale(self, env: str = "default") -> bool:
        """Whether ``env``'s generated env predates the current manifest content.

        True once a compile exists but the manifest has changed since it ran (or was synced by
        an older chefe that left no marker), so a command can recompile before activating rather
        than serve env vars and deps from a stale `.chefe/`. A workspace with nothing compiled
        yet is not stale, since first provisioning is `install`'s job, not a `run`'s.
        """
        if not self.pixi.manifest.exists():
            return False
        marker = self.out / f"{SYNCED}.{env}"
        return not marker.exists() or marker.read_text() != self.digest()

    def sync(self, env: str = "default") -> None:
        """Compile the manifest into the generated `{pixi.toml, package.json}` for ``env``."""
        files = GeneratedFiles(directory=self.out)
        with files.locked():
            self._compile(files, env)
        self.console.print(f"[green]synced[/green] {self.manifest.name} → {self.out.name}/")

    def _compile(self, files: GeneratedFiles, env: str) -> None:
        """Write every generated file for ``env``. The caller must already hold the lock."""
        source_digest = self.digest()
        manifest = self.load()
        compiled = PixiManifest.from_manifest(manifest).to_toml()
        resolution_digest = self._resolution_digest(manifest)
        try:
            existing = self.pixi.manifest.read_text(encoding="utf-8")
            resolution_manifest_changed = self._resolution_manifest(
                existing
            ) != self._resolution_manifest(compiled)
        except FileNotFoundError:
            resolution_manifest_changed = False
        try:
            resolution_changed = (self.out / _RESOLUTION_INPUTS).read_text(
                encoding="utf-8"
            ) != resolution_digest
        except FileNotFoundError:
            resolution_changed = True
        # Mark the lock stale rather than deleting it. Deleting takes the whole workspace down
        # for every other process until someone completes a solve, which on a shared machine is
        # minutes, and a solve that then fails leaves nothing to fall back to. The marker gates
        # `install` exactly as the missing file did, while `run` keeps working against the
        # environment it already had.
        if (resolution_manifest_changed or resolution_changed) and self.pixi.lock.exists():
            files.write(self.out / _RESOLUTION_STALE, resolution_digest)
            self.console.print(
                "[yellow]stale[/yellow] pixi.lock, resolution inputs changed, "
                "run `chefe install --resolve`"
            )
        files.write(self.pixi.manifest, compiled)
        files.write(self.out / _RESOLUTION_INPUTS, resolution_digest)
        if manifest.workspace.dotenv:
            files.write(self.out / DOTENV, DOTENV_SH)
        node = self.node(manifest, env)
        if (package := PackageJson.from_manifest(manifest, env, current_platform())) is not None:
            files.write(node.manifest, package.to_json())
        else:
            # The last nodejs dep is gone; a stale package.json would keep reinstalling it.
            node.manifest.unlink(missing_ok=True)
        # The marker is replaced last, after every file from this manifest is visible.
        files.write(self.out / f"{SYNCED}.{env}", source_digest)

    def install(
        self,
        env: str = "default",
        activate_only: Annotated[bool, Parameter(name="--activate-only")] = False,
        resolve: Annotated[bool, Parameter(name="--resolve")] = False,
    ) -> None:
        """Sync, then make ``env`` match the manifest across every language/toolchain.

        Always (re)generates the per-host `activate.sh` so a job or interactive shell can
        `source .chefe/activate.sh && python -m ...`. `--activate-only` skips the package
        install and just refreshes that script against the already-provisioned env. An existing
        lock is required by default. `--resolve` explicitly permits updating it on this machine.

        The whole provisioning runs under the workspace lock, not just the compile. Several
        agents share one checkout here, and holding the lock only across the compile let one
        process rewrite the manifest while another was still solving against it, which is how a
        workspace ends up with a manifest and a lock that disagree.
        """
        if not activate_only:
            files = GeneratedFiles(directory=self.out)
            with files.locked():
                self._compile(files, env)
                self.console.print(
                    f"[green]synced[/green] {self.manifest.name} → {self.out.name}/"
                )
                stale = self.out / _RESOLUTION_STALE
                if stale.exists() and not resolve:
                    raise ChefeError(
                        "pixi.lock no longer matches the resolution inputs. Run "
                        "`chefe install --resolve` on a solve-capable machine."
                    )
                self.pixi.install(env, resolve=resolve)
                # Only a solve that returned without raising has produced a lock that matches.
                stale.unlink(missing_ok=True)
                with self.activated(env):
                    self.node(self.load(), env)("install")
                crates = self.rust_deps(env)
                self.cargo.sync(env, crates)
            self.console.print(markup(t"[green]installed[/green] env [bold]{env}[/bold]"))
        self.activate(env)

    def activate(self, env: str = "default") -> Path:
        """Generate `.chefe/activate.sh` for this host and return its path.

        Writes the manifest's `[modules]` `name = version` pairs as `module purge` + `module
        load name/version ...` (guarded so it no-ops off a cluster), followed by the pixi
        activation, so a job or interactive shell can `source .chefe/activate.sh && python -m ...`.
        """
        self.out.mkdir(exist_ok=True)
        modules = self.load().modules.specs()
        Environment(self.activate_path, self.pixi.shell_hook(env)).write(modules)
        chosen = ", ".join(modules) if modules else "pixi env only (no modules)"
        self.console.print(
            markup(t"[green]wrote[/green] {self.activate_path} · modules: [bold]{chosen}[/bold]")
        )
        return self.activate_path

    def update(self, env: str = "default") -> None:
        """Re-solve to the newest allowed versions across ecosystems."""
        self._update_all(env)
        self.console.print(markup(t"[green]updated[/green] env [bold]{env}[/bold]"))

    def _update_all(self, env: str) -> None:
        """Refresh Pixi, Node, and Cargo packages within one environment's constraints."""
        self.sync(env)
        self.pixi("update", "-e", env)
        with self.activated(env):
            self.node(self.load(), env)("update")
        self.cargo.update(env, self.rust_deps(env))

    def rust_deps(self, env: str) -> dict[str, Spec]:
        """Cargo-installable crate specs declared by `[rust]` for ``env``."""
        manifest = self.load()
        rust = manifest.toolchains_for(env, current_platform()).get("rust")
        return rust.all_deps() if rust else {}

    def clean(self) -> None:
        """Remove the generated env and manifests."""
        shutil.rmtree(self.out, ignore_errors=True)
        self.console.print(f"[green]removed[/green] {self.out.name}/")

    def run(self, *argv: Annotated[str, Parameter(allow_leading_hyphen=True)]) -> None:
        """Run a task or installed executable inside the env, exiting with its code.

        Declared `[tasks]` come first; any other name falls through to an executable on the
        activated PATH. Both go through `pixi run` so the manifest's `[activation]` scripts
        and env vars always apply. A name that is neither fails with guidance up front,
        instead of pixi's bare command-not-found.

        A leading `--resolve` permits Pixi to update an existing lock on this machine. A leading
        `--env <name>` (or `-e <name>`) then selects a non-default `[envs.*]` environment, e.g.
        `chefe run --resolve --env serving python ...`. The whole command line is taken as one
        leading-hyphen var-positional so chefe's flags and target flags arrive verbatim. Help
        flags ride along too. `chefe run atpx --help` prints atpx's help, and this page appears
        only when no task name precedes the flag, as in `chefe run --help`.
        """
        resolve = argv[:1] == ("--resolve",)
        env, rest = self.env_from(argv[1:] if resolve else argv)
        with self.activated(env):
            head = rest[0]
            manifest = self.load()
            tasks = manifest.tasks if env == "default" else manifest.envs[env].tasks
            if head not in tasks:
                try:
                    local[head]
                except CommandNotFound as error:
                    task_table = "[tasks]" if env == "default" else f"[envs.{env}.tasks]"
                    raise ChefeError(
                        f"No task or executable named `{head}` was found in the `{env}` "
                        "environment. "
                        f"Run `chefe install`, check `chefe tree`, or add it to {task_table}."
                    ) from error
            code = self.pixi.launch("run", env, *rest, resolve=resolve)
        if code:
            raise SystemExit(code)

    def env_from(self, argv: tuple[str, ...]) -> tuple[str, tuple[str, ...]]:
        """Split a leading `--env/-e <name>` off the command line, returning `(env, rest)`.

        `rest` is the command to run with the env flag removed and must be non-empty (its
        first token is the task or executable). A missing command, an `--env` without a
        following name, or one not naming a declared `[envs.*]` is a `ChefeError` so the
        mistake fails fast rather than reaching pixi as a confusing bare error.
        """
        if argv and argv[0] in ("--env", "-e"):
            if len(argv) < 3:
                raise ChefeError("`--env` needs an environment name and a command to run.")
            env, rest = argv[1], argv[2:]
        else:
            env, rest = "default", argv
        if not rest:
            raise ChefeError("`chefe run` needs a task or executable to run.")
        if env != "default" and env not in self.load().envs:
            declared = ", ".join(sorted(self.load().envs)) or "(none)"
            raise ChefeError(
                f"No environment `{env}` is declared. Add an `[envs.{env}]` table or use one of: "
                f"{declared}."
            )
        return env, rest

    def x(
        self,
        *args: Annotated[str, Parameter(allow_leading_hyphen=True)],
        with_: tuple[str, ...] = (),
    ) -> None:
        """Run a command in a throwaway env, like uvx or pipx run; no manifest needed.

        args: the command and its arguments, e.g. `chefe x ruff check .`.
        with_: extra packages to make available, e.g. `--with build`.
        """
        if code := self.pixi.exec(with_, args):
            raise SystemExit(code)

    def shell(self, env: str = "default", resolve: bool = False) -> None:
        """Open an activated shell in ``env``, exiting with the shell's own status."""
        with self.activated(env):
            code = self.pixi.enter(env, resolve=resolve)
        if code:
            raise SystemExit(code)

    def add(
        self,
        *packages: str,
        language: Annotated[
            str,
            Parameter(
                name=("--language", "-l"),
                help="conda, python, or any runtime/toolchain declared in [deps].",
            ),
        ] = "conda",
        env: str = "",
        spec: str = "*",
    ) -> None:
        """Add packages to the manifest, then sync and provision so they run right away.

        `language`: `conda`, `python`, or any runtime declared in `[deps]`.
        """
        if not packages:
            raise ChefeError("No packages given. Usage: `chefe add <package> [-l language]`.")
        self.editable_manifest()
        source = next(
            (
                name
                for name, runtimes in ToolchainSpec.RUNTIME_PACKAGES.items()
                if language in runtimes
            ),
            language,
        )
        self.require_language(self.load(), source, env)
        if source in PIXI_RESOLVED:
            self.sync()
            self.pixi(
                "add", *self.package_specs(packages, spec), pypi=source == "python", feature=env
            )
            self.pull()
        else:
            document = Document(self.manifest)
            document.add(source, env, packages, spec)
            document.save()
            target = env or "default"
            self.sync(target)
            self.provision(source, target)
        self.console.print(markup(t"[green]added[/green] {', '.join(packages)}"))

    def provision(self, language: str, env: str) -> None:
        """Install a freshly added `language` dep into ``env``, so `chefe run` finds it at once.

        `pixi add` installs what it adds, and this is the counterpart for the toolchains chefe
        drives itself: without it, an added nodejs/rust dep sat in the manifest until the next
        full `chefe install` and `chefe run <bin>` failed with command-not-found. A toolchain
        with no backend of its own still provisions on the next `chefe install`.
        """
        if language == "nodejs":
            with self.activated(env):
                self.node(self.load(), env)("install")
        if language == "rust":
            self.cargo.sync(env, self.rust_deps(env))

    @staticmethod
    def package_specs(packages: tuple[str, ...], spec: str) -> tuple[str, ...]:
        """Package args with a shared version spec, in the form Pixi expects."""
        return packages if spec in ("", "*") else tuple(f"{package}{spec}" for package in packages)

    def require_language(self, manifest: Manifest, language: str, env: str) -> None:
        """Validate that a non-Pixi language is declared before writing its package table.

        The language name doubles as the manifest's dependency source table, so an env-scoped
        language may be declared either in the env or at the root `[deps]`.
        """
        if language == "conda":
            return
        scope = manifest if not env else manifest.envs.get(env)
        table = "[deps]" if not env else f"[envs.{env}.deps]"
        if scope is None:
            raise ChefeError(
                f"Environment `{env}` does not exist. "
                f'Declare `{language} = "*"` under {table} before using `-l {language}`.'
            )
        declared = set(scope.deps) | set(manifest.deps)
        runtimes = ToolchainSpec.RUNTIME_PACKAGES.get(language, frozenset({language}))
        if runtimes.isdisjoint(declared):
            raise ChefeError(
                f"Language `{language}` is not declared in {table}. "
                f'Add `{language} = "*"` there before using `-l {language}`.'
            )

    def upgrade(self, *packages: str, env: str = "") -> None:
        """Update safely within constraints, or loosen constraints for named packages."""
        self.editable_manifest()
        target = env or "default"
        if not packages:
            self._update_all(target)
            self.console.print(
                markup(
                    t"[green]upgraded[/green] every ecosystem in env "
                    t"[bold]{target}[/bold] within constraints"
                )
            )
            return
        self.sync(target)
        self.pixi("upgrade", *packages, feature=env)
        self.pull()
        self.console.print(markup(t"[green]upgraded[/green] {', '.join(packages)}"))

    def remove(self, *packages: str) -> None:
        """Remove packages from the manifest wherever declared, then re-sync."""
        self.editable_manifest()
        document = Document(self.manifest)
        removed = document.remove(packages)
        document.save()
        gone = ", ".join(dict.fromkeys(removed)) or "(nothing found)"
        self.console.print(markup(t"[green]removed[/green] {gone}"))
        self.sync()

    def pull(self) -> None:
        """Mirror pixi's resolved deps back into the manifest."""
        document = Document(self.manifest)
        document.pull(tomlkit.parse(self.pixi.manifest.read_text()).unwrap())
        document.save()

    def installed_by_source(self, env: str) -> dict[str, dict[str, str]]:
        """Installed versions for ``env`` grouped by manifest source (conda/python/nodejs/rust).

        Each ecosystem is queried through its own backend, and pixi's `pypi` kind is folded onto
        the `python` source so a declared dep lines up with what got provisioned for it.
        """
        node = self.node(self.load(), env)
        by_source: dict[str, dict[str, str]] = {
            "nodejs": {n: i.shown_version for n, i in node.installed(env).items()},
            "rust": {n: i.shown_version for n, i in self.cargo.installed(env).items()},
        }
        for name, inst in self.pixi.installed(env).items():
            source = KIND_SOURCES.get(inst.kind, inst.kind)
            installed_name = canonicalize_name(name) if source == "python" else name
            by_source.setdefault(source, {})[installed_name] = inst.shown_version
            if inst.kind == "conda":
                by_source.setdefault("python", {}).setdefault(
                    canonicalize_name(name), inst.shown_version
                )
        return by_source

    def tree(
        self, env: str = "default", plan: Annotated[bool, Parameter(name="--plan")] = False
    ) -> None:
        """Show declared vs installed deps, each checked in its own ecosystem.

        `--plan` turns the report into a dry run: instead of the full table, it lists what a
        `chefe install` would change (install the missing, update the drifted, remove the
        explicit deps no longer declared) without touching the env.
        """
        declared = self.declared(env)
        by_source = self.installed_by_source(env)
        provisioned = self.pixi.installed(env)
        if plan:
            self.report.plan(env, declared, by_source, provisioned)
        else:
            self.report.table(env, declared, by_source, provisioned)
