import hashlib
import os
import shutil
import tomllib
from collections.abc import Generator
from contextlib import contextmanager
from pathlib import Path
from typing import Annotated

import tomlkit
from cyclopts import Parameter
from plumbum import local
from plumbum.commands.processes import CommandNotFound
from pydantic import ValidationError
from rich.console import Console

from . import ENV_DIR, MANIFEST, PIXI_RESOLVED
from .backends import Cargo, Node, Pixi
from .compiled import PackageJson, PixiManifest
from .console import markup
from .environment import Environment
from .errors import ChefeError, manifest_validation_text
from .global_env import GlobalEnv
from .manifest import Document, Manifest, Spec
from .state import Declared
from .tree_report import KIND_SOURCES, TreeReport
from .utils import current_platform

# Records the manifest digest a sync compiled from, so a later command can tell when the
# generated env has gone stale against an edited manifest and recompile before activating.
SYNCED = ".synced"

# The generated per-host activation script, beside the compiled pixi manifest.
ACTIVATE = "activate.sh"

# The generated dotenv loader, sourced first by pixi activation when `workspace.dotenv` is on.
# Activation scripts run from the manifest dir (`.chefe/`), so `../.env` is the workspace root.
DOTENV = "dotenv.sh"
DOTENV_SH = (
    "#!/usr/bin/env bash\n"
    "# Generated by `chefe sync` (workspace.dotenv = true); do not edit by hand.\n"
    "set -a\n"
    '[ -f "../.env" ] && . "../.env"\n'
    "set +a\n"
)


class PackageManager:
    """A workspace: one manifest, compiled into a generated env and run by the real tools."""

    def __init__(self, root: Path | None = None) -> None:
        # Absolute so the env bin dirs put on PATH stay valid when a backend runs
        # from inside the env: a relative npm path breaks once the cwd changes.
        root = (root if root is not None else self.discover()).absolute()
        self.manifest = root / MANIFEST
        self.root = root
        self.out = root / ENV_DIR
        self.activate_path = self.out / ACTIVATE
        self.pixi = Pixi(self.out)
        self.cargo = Cargo(self.out, self.pixi)
        self.console = Console()
        self.glob = GlobalEnv(self.pixi, self.load, self.console)
        self.report = TreeReport(self.console)

    @staticmethod
    def discover(start: Path | None = None) -> Path:
        """Walk up from ``start`` (default cwd) to the nearest dir holding the manifest.

        Running chefe from a subdir should still find its workspace, the way git locates `.git`.
        Falls back to ``start`` itself when no manifest is found, so `chefe init` in a fresh dir
        still scaffolds there and `load()` later raises the actionable not-found error.
        """
        start = (start or Path()).absolute()
        for directory in (start, *start.parents):
            if (directory / MANIFEST).exists():
                return directory
        return start

    def load(self) -> Manifest:
        """The validated manifest."""
        if not self.manifest.exists():
            raise ChefeError(
                f"{self.manifest.name} not found. "
                "Run `chefe init` first, or run chefe from a workspace root."
            )
        try:
            return Manifest.load(self.manifest)
        except tomllib.TOMLDecodeError as error:
            raise ChefeError(f"{self.manifest.name} has invalid TOML: {error}") from error
        except ValidationError as error:
            raise ChefeError(manifest_validation_text(self.manifest, error)) from error

    def node(self, manifest: Manifest, env: str = "default") -> Node:
        """The Node.js backend for ``env``'s merged toolchain: manager binary plus install dir."""
        nodejs = manifest.toolchains_for(env, current_platform()).get("nodejs")
        app = nodejs.app if nodejs is not None else False
        manager = nodejs.manager if nodejs is not None and nodejs.manager else "npm"
        directory = self.root if app else self.out
        return Node(directory, manager)

    def declared(self, env: str) -> dict[str, Declared]:
        """Every dep declared for ``env`` on this host."""
        return self.load().declared(env, current_platform())

    @contextmanager
    def activated(self, env: str = "default") -> Generator[None]:
        """Expose managed ecosystem executables on PATH for commands and shells.

        Recompiles first when the manifest changed since the last sync, so an edit to
        `chefe.toml` (a new env var, a dep) is never served from a stale generated env.
        """
        if self.stale(env):
            self.console.print(
                markup(t"[yellow]{self.manifest.name} changed, recompiling[/yellow]")
            )
            self.sync(env)
        with self.pixi.activated(env):
            manifest = self.load()
            toolchains = manifest.toolchains_for(env, current_platform())
            binary_dirs = [
                self.node(manifest, env).binary_dir(),
                *[self.out / path for spec in toolchains.values() for path in spec.bin_dirs],
            ]
            path = local.env["PATH"]
            prefix = os.pathsep.join(str(path) for path in binary_dirs if path.is_dir())
            with local.env(PATH=f"{prefix}{os.pathsep}{path}" if prefix else path):
                yield

    def init(self, name: str = "") -> None:
        """Scaffold a starter manifest."""
        if self.manifest.exists():
            self.console.print(f"[yellow]{self.manifest.name} already exists[/yellow], untouched")
            return
        name = name or Path.cwd().name
        self.manifest.write_text(
            f'[workspace]\nname = "{name}"\nversion = "0.1.0"\n'
            f'platforms = ["{current_platform()}"]\n'
            'channels = ["conda-forge"]\n\n[deps]\npython = ">=3.11"\n'
        )
        self.console.print(
            markup(t"[green]created[/green] {self.manifest.name} for [bold]{name}[/bold]")
        )

    def digest(self) -> str:
        """A content hash of the manifest, the key that decides whether a compile is current."""
        return hashlib.sha256(self.manifest.read_bytes()).hexdigest()

    def stale(self, env: str = "default") -> bool:
        """Whether ``env``'s generated env predates the current manifest content.

        True once a compile exists but the manifest has changed since it ran (or was synced by
        an older chefe that left no marker), so a command can recompile before activating rather
        than serve env vars and deps from a stale `.chefe/`. A workspace with nothing compiled
        yet is not stale, since first provisioning is `install`'s job, not a `run`'s.
        """
        if not self.pixi.manifest.exists():
            return False
        marker = self.out / f"{SYNCED}.{env}"
        return not marker.exists() or marker.read_text() != self.digest()

    def sync(self, env: str = "default") -> None:
        """Compile the manifest into the generated `{pixi.toml, package.json}` for ``env``."""
        manifest = self.load()
        self.out.mkdir(exist_ok=True)
        self.pixi.manifest.write_text(PixiManifest.from_manifest(manifest).to_toml())
        if manifest.workspace.dotenv:
            (self.out / DOTENV).write_text(DOTENV_SH)
        node = self.node(manifest, env)
        if (package := PackageJson.from_manifest(manifest, env, current_platform())) is not None:
            node.manifest.write_text(package.to_json())
        else:
            # The last nodejs dep is gone; a stale package.json would keep reinstalling it.
            node.manifest.unlink(missing_ok=True)
        # Stamp the digest this compile came from so `stale()` can later spot an edited manifest.
        (self.out / f"{SYNCED}.{env}").write_text(self.digest())
        self.console.print(f"[green]synced[/green] {self.manifest.name} → {self.out.name}/")

    def install(
        self,
        env: str = "default",
        activate_only: Annotated[bool, Parameter(name="--activate-only")] = False,
    ) -> None:
        """Sync, then make ``env`` match the manifest across every language/toolchain.

        Always (re)generates the per-host `activate.sh` so a job or interactive shell can
        `source .chefe/activate.sh && python -m ...`. `--activate-only` skips the package
        install and just refreshes that script against the already-provisioned env.
        """
        if not activate_only:
            self.sync(env)
            self.pixi("install", "-e", env)
            with self.activated(env):
                self.node(self.load(), env)("install")
            crates = self.rust_deps(env)
            self.cargo.sync(env, crates)
            self.console.print(markup(t"[green]installed[/green] env [bold]{env}[/bold]"))
        self.activate(env)

    def activate(self, env: str = "default") -> Path:
        """Generate `.chefe/activate.sh` for this host and return its path.

        Writes the manifest's `[modules]` `name = version` pairs as `module purge` + `module
        load name/version ...` (guarded so it no-ops off a cluster), followed by the pixi
        activation, so a job or interactive shell can `source .chefe/activate.sh && python -m ...`.
        """
        self.out.mkdir(exist_ok=True)
        modules = self.load().modules.specs()
        Environment(self.activate_path, self.pixi.shell_hook(env)).write(modules)
        chosen = ", ".join(modules) if modules else "pixi env only (no modules)"
        self.console.print(
            markup(t"[green]wrote[/green] {self.activate_path} · modules: [bold]{chosen}[/bold]")
        )
        return self.activate_path

    def update(self, env: str = "default") -> None:
        """Re-solve to the newest allowed versions across ecosystems."""
        self.sync(env)
        self.pixi("update", "-e", env)
        with self.activated(env):
            self.node(self.load(), env)("update")
        self.console.print(markup(t"[green]updated[/green] env [bold]{env}[/bold]"))

    def rust_deps(self, env: str) -> dict[str, Spec]:
        """Cargo-installable crate specs declared by `[rust]` for ``env``."""
        manifest = self.load()
        rust = manifest.toolchains_for(env, current_platform()).get("rust")
        return rust.all_deps() if rust else {}

    def clean(self) -> None:
        """Remove the generated env and manifests."""
        shutil.rmtree(self.out, ignore_errors=True)
        self.console.print(f"[green]removed[/green] {self.out.name}/")

    def run(self, *argv: Annotated[str, Parameter(allow_leading_hyphen=True)]) -> None:
        """Run a task or installed executable inside the env, exiting with its code.

        Declared `[tasks]` come first; any other name falls through to an executable on the
        activated PATH. Both go through `pixi run` so the manifest's `[activation]` scripts
        and env vars always apply. A name that is neither fails with guidance up front,
        instead of pixi's bare command-not-found.

        A leading `--env <name>` (or `-e <name>`) selects a non-default `[envs.*]`
        environment, e.g. `chefe run --env serving python ...`. The whole command line is
        taken as one leading-hyphen var-positional so the env flag and any hyphenated
        passthrough flags reach chefe verbatim instead of being parsed as chefe options.
        Help flags ride along too. `chefe run atpx --help` prints atpx's help, and this
        page appears only when no task name precedes the flag, as in `chefe run --help`.
        """
        env, rest = self.env_from(argv)
        with self.activated(env):
            head = rest[0]
            if head not in self.load().tasks:
                try:
                    local[head]
                except CommandNotFound as error:
                    raise ChefeError(
                        f"No task or executable named `{head}` was found in the `{env}` "
                        "environment. "
                        "Run `chefe install`, check `chefe tree`, or add it to [tasks]."
                    ) from error
            code = self.pixi.exit_code("run", "-e", env, *rest)
        if code:
            raise SystemExit(code)

    def env_from(self, argv: tuple[str, ...]) -> tuple[str, tuple[str, ...]]:
        """Split a leading `--env/-e <name>` off the command line, returning `(env, rest)`.

        `rest` is the command to run with the env flag removed and must be non-empty (its
        first token is the task or executable). A missing command, an `--env` without a
        following name, or one not naming a declared `[envs.*]` is a `ChefeError` so the
        mistake fails fast rather than reaching pixi as a confusing bare error.
        """
        if argv and argv[0] in ("--env", "-e"):
            if len(argv) < 3:
                raise ChefeError("`--env` needs an environment name and a command to run.")
            env, rest = argv[1], argv[2:]
        else:
            env, rest = "default", argv
        if not rest:
            raise ChefeError("`chefe run` needs a task or executable to run.")
        if env != "default" and env not in self.load().envs:
            declared = ", ".join(sorted(self.load().envs)) or "(none)"
            raise ChefeError(
                f"No environment `{env}` is declared. Add an `[envs.{env}]` table or use one of: "
                f"{declared}."
            )
        return env, rest

    def x(
        self,
        *args: Annotated[str, Parameter(allow_leading_hyphen=True)],
        with_: tuple[str, ...] = (),
    ) -> None:
        """Run a command in a throwaway env, like uvx or pipx run; no manifest needed.

        args: the command and its arguments, e.g. `chefe x ruff check .`.
        with_: extra packages to make available, e.g. `--with build`.
        """
        if code := self.pixi.exec(with_, args):
            raise SystemExit(code)

    def shell(self, env: str = "default") -> None:
        """Open an activated shell in ``env``, exiting with the shell's own status."""
        with self.activated(env):
            code = self.pixi.exit_code("shell", "-e", env)
        if code:
            raise SystemExit(code)

    def add(
        self,
        *packages: str,
        language: Annotated[
            str,
            Parameter(
                name=("--language", "-l"),
                help="conda, python, or any runtime/toolchain declared in [deps].",
            ),
        ] = "conda",
        env: str = "",
        spec: str = "*",
    ) -> None:
        """Add packages to the manifest, then sync; conda + Python resolve through pixi.

        `language`: `conda`, `python`, or any runtime declared in `[deps]`.
        """
        if not packages:
            raise ChefeError("No packages given. Usage: `chefe add <package> [-l language]`.")
        self.require_language(self.load(), language, env)
        if language in PIXI_RESOLVED:
            self.sync()
            self.pixi(
                "add", *self.package_specs(packages, spec), pypi=language == "python", feature=env
            )
            self.pull()
        else:
            document = Document(self.manifest)
            document.add(language, env, packages, spec)
            document.save()
            self.sync()
        self.console.print(markup(t"[green]added[/green] {', '.join(packages)}"))

    @staticmethod
    def package_specs(packages: tuple[str, ...], spec: str) -> tuple[str, ...]:
        """Package args with a shared version spec, in the form Pixi expects."""
        return packages if spec in ("", "*") else tuple(f"{package}{spec}" for package in packages)

    def require_language(self, manifest: Manifest, language: str, env: str) -> None:
        """Validate that a non-Pixi language is declared before writing its package table.

        The language name doubles as the manifest's dependency source table, so an env-scoped
        language may be declared either in the env or at the root `[deps]`.
        """
        if language == "conda":
            return
        scope = manifest if not env else manifest.envs.get(env)
        table = "[deps]" if not env else f"[envs.{env}.deps]"
        if scope is None:
            raise ChefeError(
                f"Environment `{env}` does not exist. "
                f'Declare `{language} = "*"` under {table} before using `-l {language}`.'
            )
        if language not in scope.deps and language not in manifest.deps:
            raise ChefeError(
                f"Language `{language}` is not declared in {table}. "
                f'Add `{language} = "*"` there before using `-l {language}`.'
            )

    def upgrade(self, *packages: str, env: str = "") -> None:
        """Bump conda + Python constraints to the latest allowed, then sync in."""
        self.sync()
        self.pixi("upgrade", *packages, feature=env)
        self.pull()
        self.console.print(
            markup(t"[green]upgraded[/green] {', '.join(packages) or 'all conda + Python deps'}")
        )

    def remove(self, *packages: str) -> None:
        """Remove packages from the manifest wherever declared, then re-sync."""
        document = Document(self.manifest)
        removed = document.remove(packages)
        document.save()
        gone = ", ".join(dict.fromkeys(removed)) or "(nothing found)"
        self.console.print(markup(t"[green]removed[/green] {gone}"))
        self.sync()

    def pull(self) -> None:
        """Mirror pixi's resolved deps back into the manifest."""
        document = Document(self.manifest)
        document.pull(tomlkit.parse(self.pixi.manifest.read_text()).unwrap())
        document.save()

    def installed_by_source(self, env: str) -> dict[str, dict[str, str]]:
        """Installed versions for ``env`` grouped by manifest source (conda/python/nodejs/rust).

        Each ecosystem is queried through its own backend, and pixi's `pypi` kind is folded onto
        the `python` source so a declared dep lines up with what got provisioned for it.
        """
        node = self.node(self.load(), env)
        by_source: dict[str, dict[str, str]] = {
            "nodejs": {n: i.shown_version for n, i in node.installed(env).items()},
            "rust": {n: i.shown_version for n, i in self.cargo.installed(env).items()},
        }
        for name, inst in self.pixi.installed(env).items():
            by_source.setdefault(KIND_SOURCES.get(inst.kind, inst.kind), {})[name] = (
                inst.shown_version
            )
        return by_source

    def tree(
        self, env: str = "default", plan: Annotated[bool, Parameter(name="--plan")] = False
    ) -> None:
        """Show declared vs installed deps, each checked in its own ecosystem.

        `--plan` turns the report into a dry run: instead of the full table, it lists what a
        `chefe install` would change (install the missing, update the drifted, remove the
        explicit deps no longer declared) without touching the env.
        """
        declared = self.declared(env)
        by_source = self.installed_by_source(env)
        provisioned = self.pixi.installed(env)
        if plan:
            self.report.plan(env, declared, by_source, provisioned)
        else:
            self.report.table(env, declared, by_source, provisioned)
