import os
import shutil
import tomllib
from collections import Counter
from collections.abc import Generator
from contextlib import contextmanager
from pathlib import Path
from typing import Annotated

import tomlkit
from cyclopts import Parameter
from plumbum import local
from pydantic import ValidationError
from rich.console import Console
from rich.table import Table

from . import ENV_DIR, MANIFEST, NAME, PIXI_RESOLVED
from .backends import Cargo, Node, Pixi
from .compiled import PackageJson, PixiManifest
from .console import markup
from .environment import Environment
from .errors import ChefeError, manifest_validation_text
from .manifest import Document, Manifest, Spec
from .state import Declared
from .utils import current_platform, satisfied

# The generated per-host activation script, beside the compiled pixi manifest.
ACTIVATE = "activate.sh"

# pixi reports Python packages as `pypi`; the manifest declares them under `[python]`.
KIND_SOURCES = {"pypi": "python"}

# The generated dotenv loader, sourced first by pixi activation when `workspace.dotenv` is on.
# Activation scripts run from the manifest dir (`.chefe/`), so `../.env` is the workspace root.
DOTENV = "dotenv.sh"
DOTENV_SH = (
    "#!/usr/bin/env bash\n"
    "# Generated by `chefe sync` (workspace.dotenv = true); do not edit by hand.\n"
    "set -a\n"
    '[ -f "../.env" ] && . "../.env"\n'
    "set +a\n"
)


class PackageManager:
    """A workspace: one manifest, compiled into a generated env and run by the real tools."""

    def __init__(self, root: Path = Path()) -> None:
        # Absolute so the env bin dirs put on PATH stay valid when a backend runs
        # from inside the env: a relative npm path breaks once the cwd changes.
        root = root.absolute()
        self.manifest = root / MANIFEST
        self.root = root
        self.out = root / ENV_DIR
        self.activate_path = self.out / ACTIVATE
        self.pixi = Pixi(self.out)
        self.cargo = Cargo(self.out, self.pixi)
        self.console = Console()

    def load(self) -> Manifest:
        """The validated manifest."""
        if not self.manifest.exists():
            raise ChefeError(
                f"{self.manifest.name} not found. "
                "Run `chefe init` first, or run chefe from a workspace root."
            )
        try:
            return Manifest.load(self.manifest)
        except tomllib.TOMLDecodeError as error:
            raise ChefeError(f"{self.manifest.name} has invalid TOML: {error}") from error
        except ValidationError as error:
            raise ChefeError(manifest_validation_text(self.manifest, error)) from error

    def node(self, manifest: Manifest, env: str = "default") -> Node:
        """The Node.js backend for ``env``'s merged toolchain: manager binary plus install dir."""
        nodejs = manifest.toolchains_for(env, current_platform()).get("nodejs")
        app = nodejs.app if nodejs is not None else False
        manager = nodejs.manager if nodejs is not None and nodejs.manager else "npm"
        directory = self.root if app else self.out
        return Node(directory, manager)

    def declared(self, env: str) -> dict[str, Declared]:
        """Every dep declared for ``env`` on this host."""
        return self.load().declared(env, current_platform())

    @contextmanager
    def activated(self, env: str = "default") -> Generator[None]:
        """Expose managed ecosystem executables on PATH for commands and shells."""
        with self.pixi.activated(env):
            manifest = self.load()
            toolchains = manifest.toolchains_for(env, current_platform())
            binary_dirs = [
                self.node(manifest, env).binary_dir(),
                *[self.out / path for spec in toolchains.values() for path in spec.bin_dirs],
            ]
            path = local.env["PATH"]
            prefix = os.pathsep.join(str(path) for path in binary_dirs if path.is_dir())
            with local.env(PATH=f"{prefix}{os.pathsep}{path}" if prefix else path):
                yield

    def init(self, name: str = "") -> None:
        """Scaffold a starter manifest."""
        if self.manifest.exists():
            self.console.print(f"[yellow]{self.manifest.name} already exists[/yellow], untouched")
            return
        name = name or Path.cwd().name
        self.manifest.write_text(
            f'[workspace]\nname = "{name}"\nversion = "0.1.0"\n'
            f'platforms = ["{current_platform()}"]\n'
            'channels = ["conda-forge"]\n\n[deps]\npython = ">=3.11"\n'
        )
        self.console.print(
            markup(t"[green]created[/green] {self.manifest.name} for [bold]{name}[/bold]")
        )

    def sync(self, env: str = "default") -> None:
        """Compile the manifest into the generated `{pixi.toml, package.json}` for ``env``."""
        manifest = self.load()
        self.out.mkdir(exist_ok=True)
        self.pixi.manifest.write_text(PixiManifest.from_manifest(manifest).to_toml())
        if manifest.workspace.dotenv:
            (self.out / DOTENV).write_text(DOTENV_SH)
        node = self.node(manifest, env)
        if (package := PackageJson.from_manifest(manifest, env, current_platform())) is not None:
            node.manifest.write_text(package.to_json())
        else:
            # The last nodejs dep is gone; a stale package.json would keep reinstalling it.
            node.manifest.unlink(missing_ok=True)
        self.console.print(f"[green]synced[/green] {self.manifest.name} → {self.out.name}/")

    def install(
        self,
        env: str = "default",
        activate_only: Annotated[bool, Parameter(name="--activate-only")] = False,
    ) -> None:
        """Sync, then make ``env`` match the manifest across every language/toolchain.

        Always (re)generates the per-host `activate.sh` so a job or interactive shell can
        `source .chefe/activate.sh && python -m ...`. `--activate-only` skips the package
        install and just refreshes that script against the already-provisioned env.
        """
        if not activate_only:
            self.sync(env)
            self.pixi("install", "-e", env)
            with self.activated(env):
                self.node(self.load(), env)("install")
            crates = self.rust_deps(env)
            self.cargo.sync(env, crates)
            self.console.print(markup(t"[green]installed[/green] env [bold]{env}[/bold]"))
        self.activate(env)

    def activate(self, env: str = "default") -> Path:
        """Generate `.chefe/activate.sh` for this host and return its path.

        Writes the manifest's `[modules]` `name = version` pairs as `module purge` + `module
        load name/version ...` (guarded so it no-ops off a cluster), followed by the pixi
        activation, so a job or interactive shell can `source .chefe/activate.sh && python -m ...`.
        """
        self.out.mkdir(exist_ok=True)
        modules = self.load().modules.specs()
        Environment(self.activate_path, self.pixi.shell_hook(env)).write(modules)
        chosen = ", ".join(modules) if modules else "pixi env only (no modules)"
        self.console.print(
            markup(t"[green]wrote[/green] {self.activate_path} · modules: [bold]{chosen}[/bold]")
        )
        return self.activate_path

    def update(self, env: str = "default") -> None:
        """Re-solve to the newest allowed versions across ecosystems."""
        self.sync(env)
        self.pixi("update", "-e", env)
        with self.activated(env):
            self.node(self.load(), env)("update")
        self.console.print(markup(t"[green]updated[/green] env [bold]{env}[/bold]"))

    def rust_deps(self, env: str) -> dict[str, Spec]:
        """Cargo-installable crate specs declared by `[rust]` for ``env``."""
        manifest = self.load()
        rust = manifest.toolchains_for(env, current_platform()).get("rust")
        return rust.all_deps() if rust else {}

    def clean(self) -> None:
        """Remove the generated env and manifests."""
        shutil.rmtree(self.out, ignore_errors=True)
        self.console.print(f"[green]removed[/green] {self.out.name}/")

    def global_install(self, name: str = "") -> None:
        """Install every language/toolchain's declared deps into one shared global pixi env.

        Conda goes through `pixi global`; adapters then use binaries from that global env for
        languages that need a second install step, such as Python, Node.js, and Rust.
        """
        manifest = self.load()
        name = name or manifest.workspace.name

        def spec(pkg: str, dep: Spec) -> str:
            version = dep.version
            if version is None or version == "*":
                return pkg
            # A bare pin like "3.11" needs an operator, or it reads as part of the name.
            return f"{pkg}{version}" if version[0] in "<>=!~" else f"{pkg}=={version}"

        toolchains = manifest.toolchains()
        conda = dict(manifest.deps)
        self.pixi.global_install(name, [spec(pkg, dep) for pkg, dep in conda.items()])

        prefix = self.pixi.global_prefix(name)
        if (python := toolchains.get("python")) and python.all_deps():
            self.pixi.global_pip(prefix, [spec(p, d) for p, d in python.all_deps().items()])
        if (nodejs := toolchains.get("nodejs")) and nodejs.all_deps():
            self.pixi.global_npm(
                prefix,
                [
                    p if d.version in (None, "*") else f"{p}@{d.version}"
                    for p, d in nodejs.all_deps().items()
                ],
            )
        if (rust := toolchains.get("rust")) and rust.all_deps():
            self.pixi.global_cargo(prefix, list(rust.all_deps()))

        total = sum(
            len(group)
            for group in (
                manifest.deps,
                *(toolchain.all_deps() for toolchain in toolchains.values()),
            )
        )
        self.console.print(
            markup(t"[green]installed[/green] {total} deps into [bold]{name}[/bold]")
        )

    def run(self, task: str, *args: Annotated[str, Parameter(allow_leading_hyphen=True)]) -> None:
        """Run a task or installed executable inside the env, exiting with its code."""
        with self.activated():
            code = self.pixi.exit_code("run", task, *args)
        if code:
            raise SystemExit(code)

    def x(
        self,
        *args: Annotated[str, Parameter(allow_leading_hyphen=True)],
        with_: tuple[str, ...] = (),
    ) -> None:
        """Run a command in a throwaway env, like uvx or pipx run; no manifest needed.

        args: the command and its arguments, e.g. `chefe x ruff check .`.
        with_: extra packages to make available, e.g. `--with build`.
        """
        if code := self.pixi.exec(with_, args):
            raise SystemExit(code)

    def shell(self, env: str = "default") -> None:
        """Open an activated shell in ``env``, exiting with the shell's own status."""
        with self.activated(env):
            code = self.pixi.exit_code("shell", "-e", env)
        if code:
            raise SystemExit(code)

    def add(
        self,
        *packages: str,
        language: Annotated[
            str,
            Parameter(
                name=("--language", "-l"),
                help="conda, python, or any runtime/toolchain declared in [deps].",
            ),
        ] = "conda",
        env: str = "",
        spec: str = "*",
    ) -> None:
        """Add packages to the manifest, then sync; conda + Python resolve through pixi.

        `language`: `conda`, `python`, or any runtime declared in `[deps]`.
        """
        if not packages:
            raise ChefeError("No packages given. Usage: `chefe add <package> [-l language]`.")
        self.require_language(self.load(), language, env)
        if language in PIXI_RESOLVED:
            self.sync()
            self.pixi(
                "add", *self.package_specs(packages, spec), pypi=language == "python", feature=env
            )
            self.pull()
        else:
            document = Document(self.manifest)
            document.add(language, env, packages, spec)
            document.save()
            self.sync()
        self.console.print(markup(t"[green]added[/green] {', '.join(packages)}"))

    @staticmethod
    def package_specs(packages: tuple[str, ...], spec: str) -> tuple[str, ...]:
        """Package args with a shared version spec, in the form Pixi expects."""
        return packages if spec in ("", "*") else tuple(f"{package}{spec}" for package in packages)

    def require_language(self, manifest: Manifest, language: str, env: str) -> None:
        """Validate that a non-Pixi language is declared before writing its package table.

        The language name doubles as the manifest's dependency source table, so an env-scoped
        language may be declared either in the env or at the root `[deps]`.
        """
        if language == "conda":
            return
        scope = manifest if not env else manifest.envs.get(env)
        table = "[deps]" if not env else f"[envs.{env}.deps]"
        if scope is None:
            raise ChefeError(
                f"Environment `{env}` does not exist. "
                f'Declare `{language} = "*"` under {table} before using `-l {language}`.'
            )
        if language not in scope.deps and language not in manifest.deps:
            raise ChefeError(
                f"Language `{language}` is not declared in {table}. "
                f'Add `{language} = "*"` there before using `-l {language}`.'
            )

    def upgrade(self, *packages: str, env: str = "") -> None:
        """Bump conda + Python constraints to the latest allowed, then sync in."""
        self.sync()
        self.pixi("upgrade", *packages, feature=env)
        self.pull()
        self.console.print(
            markup(t"[green]upgraded[/green] {', '.join(packages) or 'all conda + Python deps'}")
        )

    def remove(self, *packages: str) -> None:
        """Remove packages from the manifest wherever declared, then re-sync."""
        document = Document(self.manifest)
        removed = document.remove(packages)
        document.save()
        gone = ", ".join(dict.fromkeys(removed)) or "(nothing found)"
        self.console.print(markup(t"[green]removed[/green] {gone}"))
        self.sync()

    def pull(self) -> None:
        """Mirror pixi's resolved deps back into the manifest."""
        document = Document(self.manifest)
        document.pull(tomlkit.parse(self.pixi.manifest.read_text()).unwrap())
        document.save()

    @staticmethod
    def row_status(spec: str, version: str | None) -> tuple[str, str, str]:
        """The (mark, shown version, tally bucket) for a declared dep vs what's installed."""
        if version is None:
            return "[red]✗ missing[/red]", "[dim]·[/dim]", "missing"
        if satisfied(spec, version):
            return "[green]✓[/green]", version, "ok"
        return "[yellow]≠ drift[/yellow]", f"[yellow]{version}[/yellow]", "drift"

    def tree(self, env: str = "default") -> None:
        """Show declared vs installed deps, each checked in its own ecosystem."""
        declared = self.declared(env)
        provisioned = self.pixi.installed(env)
        node_installed = {
            n: inst.version for n, inst in self.node(self.load(), env).installed(env).items()
        }
        cargo_installed = {name: inst.version for name, inst in self.cargo.installed(env).items()}
        by_source: dict[str, dict[str, str]] = {
            "nodejs": node_installed,
            "rust": cargo_installed,
        }
        for name, inst in provisioned.items():
            by_source.setdefault(KIND_SOURCES.get(inst.kind, inst.kind), {})[name] = inst.version
        table = Table(title=f"{NAME} · {env} · declared vs installed", header_style="bold cyan")
        for column in ("package", "language", "declared", "installed", ""):
            table.add_column(column)
        tally: Counter[str] = Counter()
        for name, dep in sorted(declared.items()):
            installed = by_source.get(dep.source, {}).get(name)
            mark, shown, bucket = self.row_status(dep.spec, installed)
            tally[bucket] += 1
            table.add_row(name, dep.source, dep.spec, shown, mark)
        self.console.print(table)
        transitive = sum(1 for inst in provisioned.values() if not inst.explicit)
        self.console.print(
            f"[green]{tally['ok']} ok[/green] · [yellow]{tally['drift']} drift[/yellow] · "
            f"[red]{tally['missing']} missing[/red] · [dim]{transitive} transitive installed[/dim]"
        )
