import hashlib
import tomllib

from rich.console import Console

from ..backends import Node, Pixi
from ..compiled import PackageJson, PixiManifest
from ..core import ChefeError, Project, Toml, current_platform
from ..manifest import Manifest
from .generated import GeneratedFiles, Writer
from .layout import Workspace
from .state import SyncState

# Freshness truth lives in one atomically-replaced state file (see
# `state.SyncState`); the compiler reads a coherent snapshot and writes the
# whole next snapshot in a single replace, never a partial marker.

# The generated dotenv loader, sourced first by pixi activation when `workspace.dotenv` is on.
# Activation scripts run from the manifest dir (`.chefe/`), so `../.env` is the workspace root.
_DOTENV = "dotenv.sh"
_DOTENV_SH = """#!/usr/bin/env bash
# Generated by `chefe sync` (workspace.dotenv = true); do not edit by hand.
# Precedence: a variable already exported in the shell wins; `.env` only fills gaps.
snapshot="$(mktemp)"
export -p > "$snapshot"
set -a
[ -f "../.env" ] && . "../.env"
set +a
. "$snapshot" 2>/dev/null || true
rm -f "$snapshot"
unset snapshot
"""


class Compiler:
    """Turns the manifest into the generated `.chefe/` env, and says when that env is stale.

    A compile writes the pixi manifest, the dotenv loader, the generated `package.json`, and the
    digest marker that later commands compare against. Nothing here provisions anything, so the
    same write runs under `sync`'s short lock and inside `install`'s longer one.
    """

    def __init__(self, workspace: Workspace, pixi: Pixi, console: Console) -> None:
        self.workspace = workspace
        self.pixi = pixi
        self.console = console

    def announce(self) -> None:
        """Report the compile that just landed, naming the manifest and the generated dir."""
        manifest = self.workspace.manifest.name
        self.console.print(f"[green]synced[/green] {manifest} → {self.workspace.out.name}/")

    def install_locked(self, files: Writer, env: str, *, resolve: bool) -> None:
        """Install ``env`` and bless its lock, in the one order that keeps the state honest.

        A stale flag refuses the install outright unless this machine may solve, and it is
        cleared only after a solve returned without raising, so a failed install can never leave
        a lock that nothing on disk vouches for looking fresh.
        """
        state = SyncState.load(self.workspace.out)
        if state.resolution_stale and not resolve:
            raise ChefeError(
                "pixi.lock no longer matches the resolution inputs. Run "
                "`chefe install --resolve` on a solve-capable machine."
            )
        self.pixi.install(env, resolve=resolve)
        if state.resolution_stale:
            self.__persist_state(files, state.model_copy(update={"resolution_stale": False}))

    def stale(self, env: str = "default") -> bool:
        """Whether ``env``'s generated env predates the current manifest content.

        True once a compile exists but the manifest has changed since it ran (or was synced by
        an older chefe that left no marker), so a command can recompile before activating rather
        than serve env vars and deps from a stale `.chefe/`. A workspace with nothing compiled
        yet is not stale, since first provisioning is `install`'s job, not a `run`'s.
        """
        if not self.pixi.manifest.exists():
            return False
        return SyncState.load(self.workspace.out).envs.get(env) != self.workspace.digest()

    def sync(self, env: str = "default") -> None:
        """Compile the manifest into the generated `{pixi.toml, package.json}` for ``env``."""
        with GeneratedFiles(directory=self.workspace.out).locked() as files:
            self.write(files, env)
        self.announce()

    def write(self, files: Writer, env: str) -> None:
        """Write every generated file for ``env``, through the writer the sync lock hands out."""
        # The digest is taken before the parse, so an edit landing mid-compile leaves the
        # workspace stale rather than blessing output built from content nobody compiled.
        source_digest = self.workspace.digest()
        manifest = self.workspace.load()
        compiled = PixiManifest.from_manifest(manifest).to_toml()
        resolution_digest = self._resolution_digest(manifest)
        state = SyncState.load(self.workspace.out)
        if self._resolution_drifted(state, compiled, resolution_digest=resolution_digest):
            state = state.model_copy(update={"resolution_stale": self.pixi.lock.exists()})
            if state.resolution_stale:
                self.console.print(
                    "[yellow]stale[/yellow] pixi.lock, resolution inputs changed, "
                    "run `chefe install --resolve`"
                )
        self._write_generated_files(files, manifest, compiled=compiled, env=env)
        # A crash anywhere above must leave the workspace stale, so the state snapshot only
        # lands once every file compiled from this manifest is already on disk, and it lands
        # as ONE atomic replace carrying digest, inputs, and stale flag together.
        self.__persist_state(
            files,
            state.model_copy(
                update={
                    "envs": {**state.envs, env: source_digest},
                    "resolution_inputs": resolution_digest,
                }
            ),
        )

    @staticmethod
    def _resolution_manifest(text: str) -> dict[str, Toml]:
        """Return generated Pixi data that can affect dependency resolution."""
        document = tomllib.loads(text)
        document.pop("tasks", None)
        return document

    def _resolution_digest(self, manifest: Manifest) -> str:
        """Hash local project metadata that can change without changing the compiled manifest."""
        digest = hashlib.sha256()
        for declared in manifest.local_python_projects():
            project = self.workspace.root / declared / Project.pyproject
            digest.update(declared.encode())
            try:
                digest.update(project.read_bytes())
            except FileNotFoundError:
                digest.update(b"\0")
        return digest.hexdigest()

    def _resolution_drifted(
        self, state: SyncState, compiled: str, *, resolution_digest: str
    ) -> bool:
        """Whether ``compiled`` or its resolution inputs differ from what was generated last.

        A generated file that is missing counts as drift, since nothing on disk can vouch for
        the lock that is already there.
        """
        try:
            existing = self.pixi.manifest.read_text(encoding="utf-8")
        except FileNotFoundError:
            existing = compiled
        if self._resolution_manifest(existing) != self._resolution_manifest(compiled):
            return True
        return state.resolution_inputs != resolution_digest

    def _write_generated_files(
        self, files: Writer, manifest: Manifest, *, compiled: str, env: str
    ) -> None:
        """Write the compiled pixi manifest, the dotenv loader, and `package.json`."""
        files.write(self.pixi.manifest, compiled)
        if manifest.workspace.dotenv:
            files.write(self.workspace.out / _DOTENV, _DOTENV_SH)
        self._write_package_json(files, manifest, env)

    def __persist_state(self, files: Writer, state: SyncState) -> None:
        """Replace the whole state snapshot in one atomic write."""
        files.write(SyncState.path(self.workspace.out), state.render())

    def _write_package_json(self, files: Writer, manifest: Manifest, env: str) -> None:
        """Write ``env``'s generated `package.json`, removing it once the last nodejs dep is gone.

        A stale `package.json` would keep reinstalling a dependency the manifest no longer
        declares, so the file is deleted rather than left behind.
        """
        node = Node.for_env(manifest, env, root=self.workspace.root, out=self.workspace.out)
        package = PackageJson.from_manifest(manifest, env=env, platform=current_platform())
        if package is None:
            files.remove(node.manifest)
            return
        files.write(node.manifest, package.to_json())
