import hashlib
import tomllib

from rich.console import Console

from ..backends import Node, Pixi
from ..compiled import PackageJson, PixiManifest
from ..core import ChefeError, Project, Toml, current_platform
from ..manifest import Manifest
from .generated import GeneratedFiles, Writer
from .layout import Workspace

# Records the manifest digest a sync compiled from, so a later command can tell when the
# generated env has gone stale against an edited manifest and recompile before activating.
_SYNCED = ".synced"

# A local path dependency can change its own pyproject without touching chefe.toml, which is the
# one way the lock drifts while the compiled manifest stays byte-identical, so that metadata is
# digested separately here.
_RESOLUTION_INPUTS = ".resolution-inputs"

# Present when the lock no longer matches the resolution inputs. Written instead of deleting
# `pixi.lock`, so a shared workspace keeps a usable lock while one process solves.
_RESOLUTION_STALE = ".resolution-stale"

# The generated dotenv loader, sourced first by pixi activation when `workspace.dotenv` is on.
# Activation scripts run from the manifest dir (`.chefe/`), so `../.env` is the workspace root.
_DOTENV = "dotenv.sh"
_DOTENV_SH = """#!/usr/bin/env bash
# Generated by `chefe sync` (workspace.dotenv = true); do not edit by hand.
set -a
[ -f "../.env" ] && . "../.env"
set +a
"""


class Compiler:
    """Turns the manifest into the generated `.chefe/` env, and says when that env is stale.

    A compile writes the pixi manifest, the dotenv loader, the generated `package.json`, and the
    digest marker that later commands compare against. Nothing here provisions anything, so the
    same write runs under `sync`'s short lock and inside `install`'s longer one.
    """

    def __init__(self, workspace: Workspace, pixi: Pixi, console: Console) -> None:
        self.workspace = workspace
        self.pixi = pixi
        self.console = console

    def announce(self) -> None:
        """Report the compile that just landed, naming the manifest and the generated dir."""
        manifest = self.workspace.manifest.name
        self.console.print(f"[green]synced[/green] {manifest} → {self.workspace.out.name}/")

    def install_locked(self, env: str, *, resolve: bool) -> None:
        """Install ``env`` and bless its lock, in the one order that keeps the marker honest.

        A stale marker refuses the install outright unless this machine may solve, and it is
        cleared only after a solve returned without raising, so a failed install can never leave
        a lock that nothing on disk vouches for looking fresh.
        """
        if (self.workspace.out / _RESOLUTION_STALE).exists() and not resolve:
            raise ChefeError(
                "pixi.lock no longer matches the resolution inputs. Run "
                "`chefe install --resolve` on a solve-capable machine."
            )
        self.pixi.install(env, resolve=resolve)
        (self.workspace.out / _RESOLUTION_STALE).unlink(missing_ok=True)

    def stale(self, env: str = "default") -> bool:
        """Whether ``env``'s generated env predates the current manifest content.

        True once a compile exists but the manifest has changed since it ran (or was synced by
        an older chefe that left no marker), so a command can recompile before activating rather
        than serve env vars and deps from a stale `.chefe/`. A workspace with nothing compiled
        yet is not stale, since first provisioning is `install`'s job, not a `run`'s.
        """
        if not self.pixi.manifest.exists():
            return False
        marker = self.workspace.out / f"{_SYNCED}.{env}"
        return not marker.exists() or marker.read_text() != self.workspace.digest()

    def sync(self, env: str = "default") -> None:
        """Compile the manifest into the generated `{pixi.toml, package.json}` for ``env``."""
        with GeneratedFiles(directory=self.workspace.out).locked() as files:
            self.write(files, env)
        self.announce()

    def write(self, files: Writer, env: str) -> None:
        """Write every generated file for ``env``, through the writer the sync lock hands out."""
        # The digest is taken before the parse, so an edit landing mid-compile leaves the
        # workspace stale rather than blessing output built from content nobody compiled.
        source_digest = self.workspace.digest()
        manifest = self.workspace.load()
        compiled = PixiManifest.from_manifest(manifest).to_toml()
        resolution_digest = self._resolution_digest(manifest)
        self._mark_lock_stale_if_drifted(files, compiled, resolution_digest=resolution_digest)
        self._write_generated_files(
            files, manifest, compiled=compiled, resolution_digest=resolution_digest, env=env
        )
        # A crash anywhere above must leave the workspace stale, so the freshness marker only
        # lands once every other file compiled from this manifest is already on disk.
        files.write(self.workspace.out / f"{_SYNCED}.{env}", source_digest)

    @staticmethod
    def _resolution_manifest(text: str) -> dict[str, Toml]:
        """Return generated Pixi data that can affect dependency resolution."""
        document = tomllib.loads(text)
        document.pop("tasks", None)
        return document

    def _mark_lock_stale_if_drifted(
        self, files: Writer, compiled: str, *, resolution_digest: str
    ) -> None:
        """Flag `pixi.lock` stale rather than deleting it, once ``compiled`` drifts from it.

        Flagging keeps other processes on a usable environment while one solves, and a failed
        solve still falls back. The marker gates `install` as a missing lock did.
        """
        if not (
            self._resolution_drifted(compiled, resolution_digest=resolution_digest)
            and self.pixi.lock.exists()
        ):
            return
        files.write(self.workspace.out / _RESOLUTION_STALE, resolution_digest)
        self.console.print(
            "[yellow]stale[/yellow] pixi.lock, resolution inputs changed, "
            "run `chefe install --resolve`"
        )

    def _resolution_digest(self, manifest: Manifest) -> str:
        """Hash local project metadata that can change without changing the compiled manifest."""
        digest = hashlib.sha256()
        for declared in manifest.local_python_projects():
            project = self.workspace.root / declared / Project.pyproject
            digest.update(declared.encode())
            try:
                digest.update(project.read_bytes())
            except FileNotFoundError:
                digest.update(b"\0")
        return digest.hexdigest()

    def _resolution_drifted(self, compiled: str, *, resolution_digest: str) -> bool:
        """Whether ``compiled`` or its resolution inputs differ from what was generated last.

        A generated file that is missing counts as drift, since nothing on disk can vouch for
        the lock that is already there.
        """
        try:
            existing = self.pixi.manifest.read_text(encoding="utf-8")
        except FileNotFoundError:
            existing = compiled
        if self._resolution_manifest(existing) != self._resolution_manifest(compiled):
            return True
        inputs = self.workspace.out / _RESOLUTION_INPUTS
        try:
            return inputs.read_text(encoding="utf-8") != resolution_digest
        except FileNotFoundError:
            return True

    def _write_generated_files(
        self, files: Writer, manifest: Manifest, *, compiled: str, resolution_digest: str, env: str
    ) -> None:
        """Write the compiled pixi manifest, its resolution digest, dotenv, and `package.json`."""
        files.write(self.pixi.manifest, compiled)
        files.write(self.workspace.out / _RESOLUTION_INPUTS, resolution_digest)
        if manifest.workspace.dotenv:
            files.write(self.workspace.out / _DOTENV, _DOTENV_SH)
        self._write_package_json(files, manifest, env)

    def _write_package_json(self, files: Writer, manifest: Manifest, env: str) -> None:
        """Write ``env``'s generated `package.json`, removing it once the last nodejs dep is gone.

        A stale `package.json` would keep reinstalling a dependency the manifest no longer
        declares, so the file is deleted rather than left behind.
        """
        node = Node.for_env(manifest, env, root=self.workspace.root, out=self.workspace.out)
        package = PackageJson.from_manifest(manifest, env=env, platform=current_platform())
        if package is None:
            files.remove(node.manifest)
            return
        files.write(node.manifest, package.to_json())
